sut:
  build: .
  command: run_tests.sh
  environment:
    - "APP_NAME=Laravel"
    - "APP_ENV=local"
    - "APP_KEY=base64:qvxL3ijR2uwH268mkoz7B8DyuJ9mFectDiQbUy5D6/E="
    - "APP_DEBUG=true"
    - "APP_URL=http://localhost"
    - "LOG_CHANNEL=stack"
    - "DB_CONNECTION=mysql"
    - "DB_HOST=127.0.0.1"
    - "DB_PORT=3306"
    - "DB_DATABASE=homestead"
    - "DB_USERNAME=homestead"
    - "DB_PASSWORD=secret"
    - "BROADCAST_DRIVER=log"
    - "CACHE_DRIVER=file"
    - "QUEUE_CONNECTION=sync"
    - "SESSION_DRIVER=file"
    - "SESSION_LIFETIME=120"
    - "REDIS_HOST=127.0.0.1"
    - "REDIS_PASSWORD=null"
    - "REDIS_PORT=6379"
    - "MAIL_DRIVER=smtp"
    - "MAIL_HOST=smtp.mailtrap.io"
    - "MAIL_PORT=2525"
    - "MAIL_USERNAME=null"
    - "MAIL_PASSWORD=null"
    - "MAIL_ENCRYPTION=null"
    - "PUSHER_APP_ID="
    - "PUSHER_APP_KEY="
    - "PUSHER_APP_SECRET="
    - "PUSHER_APP_CLUSTER=mt1"
    - "SWOOLE_HTTP_PORT=80"
    - "SWOOLE_HTTP_HOST=0.0.0.0"
  depends_on:
    - database

database:
  image: mysql:5.7
  hostname: database
  ports:
    - "3306:3306"
  environment:
    - "MYSQL_RANDOM_ROOT_PASSWORD=yes"
    - "MYSQL_DATABASE=docker"
    - "MYSQL_USER=docker"
    - "MYSQL_PASSWORD=secret"